### ISSUE TITLE
Question | Why does coverage.mixin not use `--coverage` ?

### ISSUE THREAD

**Issue by ruffsl** [colcon/colcon-mixin-repository#19]
> --coverage
> This option is used to compile and link code instrumented for coverage analysis. The option is a synonym for -fprofile-arcs -ftest-coverage (when compiling) and -lgcov (when linking).
> https://stackoverflow.com/questions/28840261/gcov-what-is-the-difference-between-coverage-and-ftest-coverage-when-buildi

Was there a particular reason why `-lgcov (when linking)` was not included in this .mixin?

https://github.com/colcon/colcon-mixin-repository/blob/f3fcacdd8dd3620dda2ad8144962d0ab07f6932d/coverage.mixin#L4-L6

I'm unsure if this was deliberate, or a accidental omission in https://github.com/colcon/colcon-mixin-repository/pull/8 .
Would switching the coverage.mixin to use `--coverage` be more obvious for gcc users?

**Comment by dirk-thomas** [comment]
> I'm unsure if this was deliberate, or a accidental omission in #8 .
> Would switching the coverage.mixin to use --coverage be more obvious for gcc users?

@jpsamper2009

**Comment by ruffsl** [comment]
Here is the cpp cmake example from Codecov.io:

https://github.com/codecov/example-cpp11-cmake/blob/2036eaba3f3de67d8776859bcabf93484bf4adf2/CMakeLists.txt#L14-L27

**Comment by dirk-thomas** [comment]
Implemented in #20.
